### ISSUE TITLE
Make check not working under Gentoo

### ISSUE THREAD

**Issue by jurov** [PolyPasswordHasher/PolyPasswordHasher-C#7]
I got these messages from autoreconf:
```
> autoreconf-2.69 --install        
configure.ac:26: warning: macro 'AM_PATH_CHECK' not found in library
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:26: warning: macro 'AM_PATH_CHECK' not found in library
```
Newer autoreconf failed completely, with same message.

The package built fine, but make check failed:
```
(previous output snipped)
make[2]: Entering directory 'work/pph/PolyPasswordHasher-C/tests'
gcc -DHAVE_CONFIG_H -I. -I..    @CHECK_CFLAGS@ -I../include -g -O2 -MT check_libgfshare-check_libgfshare.o -MD -MP -MF .deps/check_libgfshare-check_libgfshare.Tpo -c -o check_libgfshare-check_libgfshare.o `test -f 'check_libgfshare.c' || echo './'`check_libgfshare.c
gcc: error: @CHECK_CFLAGS@: File not found
Makefile:679: recipe for target 'check_libgfshare-check_libgfshare.o' failed
```

After I added AC_CONFIG_MACRO_DIRS([m4])' to configure.ac as recommended, make check is working too.

**Comment by SantiagoTorres** [comment]
Hi,

I might have seen this before. However, I think this issue stems from the autoconf version that you are using.

Could you provide the versions of check, autoconf and gcc to see if I can repeat this bug?

Thanks for letting us know!

**Comment by jurov** [comment]
I'm using  check-0.9.11 (but autoconf produces the message regardless of library is installed or not) , autoconf 2.13 or 2.69, gcc 4.8.3

**Comment by SantiagoTorres** [comment]
Alright, now I'm able to reproduce the warnings, but not the error. I'm wondering if it's specific to something else in your environment.

In the meantime, I think that getting rid of the warnings is a good idea. Please tell me if that also fixes the error on your side.

**Comment by jurov** [comment]
Yes, it's fixed. Thanks!
